package com.data.mapper

import com.data.dto.LocationDto
import com.data.dto.UserCreateDto
import com.data.dto.UserFullDto
import com.data.dto.UserPreviewDto
import com.domain.models.Location
import com.domain.models.UserDetail
import com.domain.models.UserPreview

object UserMapper {
    fun UserPreviewDto.toDomain(): UserPreview {
        return UserPreview(
            id = this.id,
            title = this.title,
            firstName = this.firstName,
            lastName = this.lastName,
            picture = this.picture
        )
    }

    fun UserFullDto.toDomain(): UserDetail {
        return UserDetail(
            id = this.id,
            title = this.title,
            firstName = this.firstName,
            lastName = this.lastName,
            picture = this.picture,
            gender = this.gender,
            email = this.email,
            dateOfBirth = this.dateOfBirth,
            phone = this.phone,
            location = this.location?.toDomain(),
            registerDate = this.registerDate,
            updatedDate = this.registerDate, // Using registerDate as fallback
        )
    }

    fun UserDetail.toFullDto(): UserFullDto {
        return UserFullDto(
            id = this.id,
            title = this.title,
            firstName = this.firstName,
            lastName = this.lastName,
            picture = this.picture,
            gender = this.gender,
            email = this.email,
            dateOfBirth = this.dateOfBirth,
            registerDate = this.registerDate,
            phone = this.phone,
            location = this.location?.toDto(),
        )
    }

    fun UserPreview.toPreviewDto(): UserPreviewDto {
        return UserPreviewDto(
            id = this.id,
            title = this.title,
            firstName = this.firstName,
            lastName = this.lastName,
            picture = this.picture,
        )
    }

    fun UserDetail.toCreateDto(): UserCreateDto {
        return UserCreateDto(
            firstName = this.firstName,
            lastName = this.lastName,
            email = this.email,
            title = this.title.takeIf { it.isNotEmpty() },
            gender = this.gender.takeIf { it.isNotEmpty() },
            dateOfBirth = this.dateOfBirth.takeIf { it.isNotEmpty() },
            phone = this.phone.takeIf { it.isNotEmpty() },
            picture = this.picture.takeIf { it.isNotEmpty() },
            location = this.location?.toDto(),
        )
    }

    fun UserCreateDto.toDomain(): UserDetail {
        return UserDetail(
            id = "", // Will be generated by server
            title = this.title ?: "",
            firstName = this.firstName,
            lastName = this.lastName,
            picture = this.picture ?: "",
            gender = this.gender ?: "",
            email = this.email,
            dateOfBirth = this.dateOfBirth ?: "",
            phone = this.phone ?: "",
            location = this.location?.toDomain(),
            registerDate = "", // Will be set by server
            updatedDate = "", // Will be set by server
        )
    }

    fun LocationDto.toDomain(): Location {
        return Location(
            street = this.street,
            city = this.city,
            state = this.state,
            country = this.country,
            timezone = this.timezone,
        )
    }

    fun Location.toDto(): LocationDto {
        return LocationDto(
            street = this.street,
            city = this.city,
            state = this.state,
            country = this.country,
            timezone = this.timezone,
        )
    }
}
